### ISSUE TITLE
Commands not recognized

### ISSUE THREAD

**Issue by CharEmMech** [thekamilpro/kppwpush#7]
I installed the module, imported the module and your commands are available through auto discover in the session however parameter tab completion fails and cmdlets are not recognized. 

PS S:\> Import-Module kppwpush
PS S:\> New-Pwpush -payload "yo"
New-Pwpush : The term 'New-Pwpush' is not recognized as the name of a cmdlet, function, script file, or operable
program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:1
+ New-Pwpush -payload "yo"
+ ~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (New-Pwpush:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

PS S:\> Get-Command new-pwpush
Get-Command : The term 'new-pwpush' is not recognized as the name of a cmdlet, function, script file, or operable
program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:1
+ Get-Command new-pwpush
+ ~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (new-pwpush:String) [Get-Command], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException,Microsoft.PowerShell.Commands.GetCommandCommand

PS S:\> Get-Module kppwpush

ModuleType Version    Name                                ExportedCommands
---------- -------    ----                                ----------------
Script     1.3.1      kppwpush                            {Connect-KpPwpush, Get-KpPwpush, Get-KpPwpushActive, Get-K...

PS S:\> Get-Module kppwpush | select -ExpandProperty exportedcommands

Key                    Value
---                    -----
Connect-KpPwpush       Connect-KpPwpush
Get-KpPwpush           Get-KpPwpush
Get-KpPwpushActive     Get-KpPwpushActive
Get-KpPwpushExpired    Get-KpPwpushExpired
Get-KpPwpushPreview    Get-KpPwpushPreview
Get-KpPwpushUrl        Get-KpPwpushUrl
Get-KpPwpushUrlActive  Get-KpPwpushUrlActive
Get-KpPwpushUrlExpired Get-KpPwpushUrlExpired
Get-KpPwpushUrlPreview Get-KpPwpushUrlPreview
Invoke-KpPwpushRequest Invoke-KpPwpushRequest
New-KpPwpush           New-KpPwpush
New-KpPwpushUrl        New-KpPwpushUrl
Remove-KpPwpush        Remove-KpPwpush
Remove-KpPwpushUrl     Remove-KpPwpushUrl

**Comment by kamilprocyszyn** [comment]
Hi @CharEmMech all commands have a prefix of ```Kp``` hence in your example you'd like to run ```New-KpPwpush```
